# Generated by Django 6.0.1 on 2026-02-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(default='', max_length=100, verbose_name='clase')),
                ('entrytime', models.DateTimeField(default='', verbose_name='hora de entrada')),
                ('departuretime', models.DateTimeField(default='', verbose_name='hora de salida')),
                ('sites', models.PositiveSmallIntegerField(max_length=60, verbose_name='sites')),
            ],
            options={
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='fathers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('age', models.DateField(default='', verbose_name='Fecha de Nacimiento')),
                ('number', models.PositiveSmallIntegerField(max_length=12, verbose_name='Telefono')),
            ],
            options={
                'verbose_name_plural': 'Padres',
            },
        ),
        migrations.CreateModel(
            name='childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('age', models.DateField(default='0000/00/00 00:00', verbose_name='Fecha de Nacimiento')),
                ('average', models.PositiveSmallIntegerField(default=0, verbose_name='Nota Media')),
                ('school', models.ManyToManyField(to='ProyectoALmacen.classroom')),
                ('father', models.ManyToManyField(to='ProyectoALmacen.fathers')),
            ],
            options={
                'verbose_name_plural': 'Niños',
            },
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('asignature', models.CharField(verbose_name='asignatura')),
                ('classrooms', models.ManyToManyField(to='ProyectoALmacen.classroom')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
