# Generated by Django 6.0.1 on 2026-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoALmacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fathers',
            name='contrasena',
            field=models.CharField(db_column='contraseña', default='', max_length=100, verbose_name='Contrasena'),
        ),
    ]
