# Generated by Django 6.0.1 on 2026-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoALmacen', '0002_fathers_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fathers',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='teachers',
            name='contrasena',
            field=models.CharField(db_column='contraseña', default='', max_length=100, verbose_name='Contraseña'),
        ),
    ]
